const DISPATCH_METHOD = {
  START_LOADING: "START_LOADING",
  FINISH_LOADING: "FINISH_LOADING",
  FAIL_FETCH: "FAIL_FETCH",
  SUCCESS_FETCH: "SUCCESS_FETCH",
  SUCCESS_AUTHORIZATION: "SUCCESS_AUTHORIZATION",
  FAIL_AUTHORIZATION: "FAIL_AUTHORIZATION",
};

export { DISPATCH_METHOD };
